on: push
# change the above to use on > push > tags > - "v*.*.*"
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        run: echo "# Hello World" > ${{ github.workspace }}--CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          body_path: ${{ github.workspace }}--CHANGELOG.txt
          draft: false
          prerelease: false